### ISSUE TITLE
Avatars not showing up when put in the figura>avatar directory.

### ISSUE THREAD

**Issue by Dr-Sunset** [Kingdom-of-The-Moon/FiguraRewriteRewrite#1]
When an avatar is in the folder meant for them, the avatars don't show up in the mod UI. 
This is a problem for many people, and I hope there will be a solution.

**Comment by Slymeball** [comment]
You do know that a rewrite avatar now requires an `avatar.json` file to be recognized as, well, a readable Figura avatar, correct?

I have to add this to my FAQ since this is apparently "an issue for many people."

**Comment by KitCat962** [comment]
Looks like *somebody* didn't read the rewrite hellp channel

**Comment by ghost** [comment]
> You do know that a rewrite avatar now requires an `avatar.json` file to be recognized as, well, a readable Figura avatar, correct?
> 
> I have to add this to my FAQ since this is apparently "an issue for many people."

Could you please add the FAQ to the place where people are actually most likely to look at? The file named "README" in all caps, requesting the user to read the file.

This is also helpful for people who do not have Discord.
