### ISSUE TITLE
1.19.1/2 ?

### ISSUE THREAD

**Issue by x-yingcan-x** [Kingdom-of-The-Moon/FiguraRewriteRewrite#10]
maybe some mods cause crash.  [latest.log](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/files/9347868/latest.log)

**Comment by Fnige** [comment]
Do you have a crash report? or even a modlist?

**Comment by Fnige** [comment]
WAIT. Figura isnt supported on 1.19.1/2 yet (I suck at reading titles)
