### ISSUE TITLE
Cannot play custom sound

### ISSUE THREAD

**Issue by Gakuto1112** [Kingdom-of-The-Moon/FiguraRewriteRewrite#2]
## Description
For some reason, custom sounds cannot be played.
I made a simple avatar (attached to this issue) to test to play custom sound, but I could not play it.
@GNanimates ``GNamimates#2357`` helped me to solve this issue but I could not solve the probrem in the end. Please see the **#Rewrite Hellp Thread** in [Figura discord server](https://discord.gg/ekHGHcH8Af) for conversation at that time.

## How to reproduce
1. Use the avatar attached this issue.
2. Playes a custom sound with a vanilla sound if custom sound works currectly.

At least, I could not play it.

## Note
- I give my self a permission to play custom sound.
- Sound from [Otojin](https://on-jin.com/sound/sei.php?bunr=%E3%83%99%E3%83%AB%E3%83%BB%E9%90%98%E3%83%BB%E9%88%B4&kate=%E9%81%93%E5%85%B7).

## Attachments
- [test.zip](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/files/9120053/test.zip)

**Comment by Francy-chan** [comment]
~~Ogg has a lot of different codecs, see https://en.wikipedia.org/wiki/Ogg#Ogg_codecs~~
~~This issue is related to Minecraft using the codec "vorbis", while the attached sound uses a different, unsupported, codec~~

Seems like I was wrong and misjudged the issue too quickly
Since the sounds plays whitin resource packs just fine, that is considered a Figura bug

**Comment by Fnige** [comment]
Is it possible for figura to give you an error if you use the wrong codec? Probably would help others dealing with this issue.

Maybe as an extra thing, lead it to a command that gives you more info on how to get an ogg file with the right codec.

**Comment by Francy-chan** [comment]
unfortunately nope, as the sound loading is done internally in the minecraft code

the real issue is that the sounds actually load, however in game they appear completely muted

**Comment by Fnige** [comment]
What about the second half of our comment?

**Comment by Francy-chan** [comment]
that would fall into the (planned) wiki page for custom sounds

**Comment by GNamimates** [comment]
Hey look, buddy. I'm an engineer, that means I solve problems.
Not problems like "What is beauty?", 'cause that would fall within the purview of your conundrums of philosophy.
I solve practical problems!

For instance, how am I gonna stop some big mean Mother-Hubbard from tearin' me a structurally superfluous new behind?
The answer? Use a gun. And if that don't work, use more gun.
Like this, heavy-caliber tripod-mounted little-old-number designed by me.
Built, by me. And you best hope...
Not pointed at you.

**Comment by Francy-chan** [comment]
ok the issue has been fixed now and gonna be present on the next build
