### ISSUE TITLE
Add FAQ to README

### ISSUE THREAD

**Issue by ghost** [Kingdom-of-The-Moon/FiguraRewriteRewrite#3]
> You do know that a rewrite avatar now requires an `avatar.json` file to be recognized as, well, a readable Figura avatar, correct?
> 
> I have to add this to my FAQ since this is apparently "an issue for many people."

Could you please add the FAQ to the place where people are actually most likely to look at? The file named "README" in all caps, requesting the user to read the file.

This is also helpful for people who do not have Discord.

_Originally posted by @pjalsGit in https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/issues/1#issuecomment-1184597189_

**Comment by Fnige** [comment]
Or possibly link to Slyme's FAQ.

**Comment by ghost** [comment]
Looks like it has been fixed.
