### ISSUE TITLE
Incorrect error thrown from WorldAPI.newBlock

### ISSUE THREAD

**Issue by joey-drake** [Kingdom-of-The-Moon/FiguraRewriteRewrite#30]
## Issue
When passing an invalid parameter to [`WorldAPI.newBlock`](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/blob/b2b9c34e75dd0d16eeca76db73458acbe1ec8e2b/src/main/java/org/moon/figura/lua/api/world/WorldAPI.java#L352-L359), the function throws an inaccurate error.

## Cause
When [`parseVec3`](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/blob/b2b9c34e75dd0d16eeca76db73458acbe1ec8e2b/src/main/java/org/moon/figura/utils/LuaUtils.java#L44-L54) fails and throws an error it gets eaten by the try catch in `newBlock`

https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/blob/b2b9c34e75dd0d16eeca76db73458acbe1ec8e2b/src/main/java/org/moon/figura/lua/api/world/WorldAPI.java#L352-L359

![image](https://user-images.githubusercontent.com/84277847/194063814-63afa7cf-e91d-4603-a089-4a4bcb79d079.png)

**Comment by Francy-chan** [comment]
fixed at 1cfe97c
