### ISSUE TITLE
Script doesn't work after player stops existing

### ISSUE THREAD

**Issue by SkyTheNerd** [Kingdom-of-The-Moon/FiguraRewriteRewrite#4]
Before pre-5, the script would keep working after the player died, but it doesn't work now.

Before:
https://user-images.githubusercontent.com/79011616/179290575-51bffced-132f-4b7a-b45a-53b68bee73c5.mp4
After:
https://user-images.githubusercontent.com/79011616/179290661-b8bd24c3-3eb7-4ded-8e40-427e351a9bc3.mp4

**Comment by KitCat962** [comment]
This was an intended change in pre-5. the TICK event was changed to only run when the player exists, if only because people were complaining that it didnt work like prewrite. the WORLD_TICK events works like pre-4 TICK. Use that instead

**Comment by SkyTheNerd** [comment]
Okay, wasn't aware, it works now.
