### ISSUE TITLE
Immediate disconnection when "host:sendChatCommand()" runs with formatting codes included

### ISSUE THREAD

**Issue by Gakuto1112** [Kingdom-of-The-Moon/FiguraRewriteRewrite#47]
# Description
Players who uses Figura avatar will be disconnected immediately because of "Illigal characters in chat" when avatar script runs `host:sendChatCommand()` or `host:sendChatCommand()` with formatting codes included.

# How to reproduce
1. Turn on "Chat Messages".
2. Run codes like below with avatar script.
    **Note**: You cannot run this code with `/figura run <code>`.

```lua
host:sendChatCommand("§cThis text will force you to disconnect.")
```

3. You will be kicked by Minecraft server.

    ![Disconnection screen](https://user-images.githubusercontent.com/90630001/204709411-391b160f-beda-4a32-b922-b9e91cf28987.jpg)

# Expected behavior
Figura should remove formatting code when running `host:sendChatCommand()` or `host:sendChatCommand()` to prevent players from disconnecting.

# Notes
- This issue occurs even in single player because of Minecraft specifications.

**Comment by GrandpaScout** [comment]
Play stupid games win stupid prizes I guess.
This can very easily be avoided in base Lua with a simple
```lua
str = str:gsub("§[0-9a-fklmnor]?", "")
```

Also, I would advise against the suggestion as some servers *do* allow the use of the section sign in chat messages sent by players.

**Comment by Francy-chan** [comment]
Not fixing this, as the server can allow the user to input "§" or have changed the blacklisted character to another one
