### ISSUE TITLE
Instant crash with Better Combat

### ISSUE THREAD

**Issue by Nytem** [Kingdom-of-The-Moon/FiguraRewriteRewrite#50]
Better Combat: [https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus/files/4211956](url)

Error:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'Figura' (figura) 0.1.0-rc.12+1.19.2-fbd5517 (C:\Users\Nytem\AppData\Roaming\.minecraft\mods\figura-0.1.0-rc.12-1.19.2.jar).
Unmet dependency listing:
	 - Mod 'Better Combat' (bettercombat) 1.5.3+1.19 is incompatible with any version of mod 'Figura' (figura), but a matching version is present: 0.1.0-rc.12+1.19.2-fbd5517!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by GrandpaScout** [comment]
Better Combat lists "figura" as an incompatible mod.
You can get around this by opening the `fabric.mod.json` file and removing the `"figura"` entry from the `"breaks"` section.

Don't expect it to just *work* when you do this though. It likely wont.

**Comment by Francy-chan** [comment]
thats up to better combat authors to remove the break point
(see: https://github.com/ZsoltMolnarrr/BetterCombat/blob/1.19.3/fabric/src/main/resources/fabric.mod.json#L44)

besides that, the incompatibility was been resolved by the commit d604d07

**Comment by Fnige** [comment]
Here: https://github.com/ZsoltMolnarrr/BetterCombat/blob/066f2fb79e133c469c0ba3812c72b64a4409b190/fabric/src/main/resources/fabric.mod.json#L44

Though do note: https://github.com/ZsoltMolnarrr/BetterCombat/issues/71

**Comment by Nytem** [comment]
> Here: https://github.com/ZsoltMolnarrr/BetterCombat/blob/066f2fb79e133c469c0ba3812c72b64a4409b190/fabric/src/main/resources/fabric.mod.json#L44
> 
> Though do note: [ZsoltMolnarrr/BetterCombat#71](https://github.com/ZsoltMolnarrr/BetterCombat/issues/71)

I only plan on adding elements to the basic minecraft character, I wouldn't be creating a whole new player model. Would this still cause issues?

**Comment by Fnige** [comment]
> I only plan on adding elements to the basic minecraft character, I wouldn't be creating a whole new player model. Would this still cause issues?

Probably will but feel free to try

**Comment by lenrik1589** [comment]
*probably not with the latest commit* but yes, figura changes player rendering when an avatar is loaded regardless of whether it is complex or not as you might have a script that "complicates" your avatar (also do note that main branch is currently based on 1.19.3)

**Comment by Nytem** [comment]
ah alright, I'll give it a shot, worst case I lose a hat and I'd just have to make a mod to get it rather than figura.

Thanks for the super quick help everyone!

**Comment by Nytem** [comment]
my solution was to make it hide all limbs and armor if I was in first person except the arms
