### ISSUE TITLE
1.19.3 version?

### ISSUE THREAD

**Issue by TecEash1** [Kingdom-of-The-Moon/FiguraRewriteRewrite#51]
Hi, I was just wondering if a 1.19.3 version of this mod is being worked on

**Comment by TecEash1** [comment]
Also if you are, are you able to provide an ETA - if you are, great, if not np

**Comment by GrandpaScout** [comment]
Go to the `❓丨hellp-discussion` channel on the discord server and type `h?artifact`. You'll get your answer.
(tl;dr: yes, there's already a version for 1.19.3 being made)

**Comment by TecEash1** [comment]
thanks
