### ISSUE TITLE
SendChatMessage and SendChatCommand lua commands not functional

### ISSUE THREAD

**Issue by VideoGames1000** [Kingdom-of-The-Moon/FiguraRewriteRewrite#52]
Models using SendChatMessage and SendChatCommand won't run, despite everything surrounding seeming to work as intended. Even simple host:SendChatMessage("test") commands don't seem to do anything when added.

**Comment by applejuiceyy** [comment]
these functions require a permission to be enabled in the settings page

**Comment by Slymeball** [comment]
Did you remember to turn on the Chat Messages option in Settings? Although it is highly unrecommended as Figura does not stop chat signing, it can be toggled on via the option in the Dev section of Settings.

**Comment by VideoGames1000** [comment]
Ah, I figured it would be on by default, let me see if I can find those.

**Comment by VideoGames1000** [comment]
Ah, yeah, I just had it turned off, whoops. Thanks!
