### ISSUE TITLE
### FATAL ERROR ### - Ticking Screen - Who's fault is this? Yours or mine?

### ISSUE THREAD

**Issue by S0LiD-ST4T3** [Kingdom-of-The-Moon/FiguraRewriteRewrite#55]
i... Can't even understand this log, let alone explain it. here, just... take the damn thing and tell me what i did wrong, or if it's even my fault to begin with.
(Failed hybrid graphics, no discrete graphics. do NOT ask me to switch to my GPU, it literally does not work, and i'm waiting for a motherboard replacement to fix it, but it's slow.)

Neofetch, if relevant: Data Expunged. Mostly useless.

crash log/dump file below.

[crash-2023-01-24_08.10.15-client.txt](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/files/10491029/crash-2023-01-24_08.10.15-client.txt)

Addendum 1 - 3:48 PM: testing with older versions of fabric and it's Fabric API jar file. We'll see if this works.
     Results: Test gained a different crash output, but still resulted in a crash. here is the new log for
analysis. [crash-2023-01-24_15.49.12-client.txt](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/files/10494290/crash-2023-01-24_15.49.12-client.txt)
             
             
             
FINALE: turns out figura crashes if you use cracked MC. $30 down the microsoft hole just so i can buy the game for the 3rd time (i think) and convert a pre-rewrite avatar to the rewrite version. I just have to eat less food this month to pay my rent and such.

**Comment by lenrik1589** [comment]
Hello. first of all, ain't ya kinda rude?

Secondly… i can't see any code related to Figura, how did you come to the conclusion that it is a Figura bug and not FabricAPI?

**Comment by lenrik1589** [comment]
Also, telling us specific circumstances in which this crash occurs would be much more helpful than "Here, have my neofetch", as just loading a world with your mod set does not yield a crash (that is what i can induce from the report to be circumstances)

**Comment by S0LiD-ST4T3** [comment]
My mod set is just Figura and Fabric API with fabric loader 0.14.13 on 1.19.2 with LWJGL 3.3.1 and OpenJDK JRE 17
I'm going to post this to their issues board next, if this seems to be their issue.

**Comment by S0LiD-ST4T3** [comment]
I disabled figura and ended up with a stable game client. No crashes.

something isn't right.

**Comment by lenrik1589** [comment]
*Again*, what are the circumstances in which the crahses occur? (Fran, who is the main developer for this project, made a commit that might jut be related to this crash, however) using the same set (and versions) of Minecraft, Fabric loader and API, and Figura I could bot reproduce the crash with my guessed circumstances

**Comment by S0LiD-ST4T3** [comment]
I have no idea. fabric devs won't help because of.... dumb reasons... (i didn't have $30 to re-buy the game to prove i own a legit copy. total jackwagons, i say. I already had one, though it was hacked. not going over it again. I'll be buying it again when i have the money for it)  and i'm stuck between bedrock and an equally hard place.

It's likely on their end, i've had a chance to regain sanity, but i'm going to try an older release of Fabric API to see if it's just an issue with the build being way newer than figura expects.

(For the record, i will not be remaining on a cracked launcher for longer than 72hr. Please expect my status on such issues to change. Please do contact me if you have to postpone this until the purchase is completed. i don't approve of feeding microsoft more of my money though, but i'm doing what i can to satisfy your needs. besides, i'd like to play with some friends on a server anyways. i'm buying it either way)

**Comment by lenrik1589** [comment]
i can understand fabric, as if you are not using a legit launcher (which is basically almost 100% guarantee if you are using a pirated version) we can't guarantee that it is not a modification made by the launcher itself that breaks the game, and since i already tried to reproduce the crash with your mod set, it is more likely to be launcher shenanigans

**Comment by S0LiD-ST4T3** [comment]
try MultiMC - my launcher of choice is just a version of that with ely.by skin loading crap on it. (UltimMC) on linux (Ubuntu 20.04). OS probably won't matter though. just try it there, or i'll tar.gz the instance over to you

(finally, someone that doesn't stonewall me. Thank you. you are more helpful than those other jerks)

as for MY end of the testing, (Expunged. i found out on my own)

Addendum: older versions of dependencies produce different results, but all a similar display-related crash.
if it's doing something with the nvidia GPU, i'm going to cry.

pre-rewrite versions (0.0.8) worked Exceedingly well, but those versions are essentially dinosaur versions of figura at this point. Players i plan to play with are using rewrite code.

**Comment by lenrik1589** [comment]
Unfortunately, *I* cannot trust in legitimacy of the modifications provided by UltimMC as it seems they patch in their own Authentication services instead of just not authenticating the player at all, meaning that you are not running known to work with fabric or any other loader in general copy of the game, which in turn means we cannot verify what causes the issue definitively

**Comment by S0LiD-ST4T3** [comment]
Can only mean one thing. I need to either find a cheap alt somewhere, or scrounge up cash to buy the game.

but i'm going to try stock MultiMC next time, THEN i'll try something more official, since it's easier to to MultiMC. (Ubuntu sucks to manually install forge to minecraft on)

Mark this however you need to, but i will end up replying with my findings again if i make any more progress.

If resolved, i want others to have these details for future reference if anyone else has the same problems as i am.

**Comment by lenrik1589** [comment]
If you *are* using ely.by for skins and authentication, they only seem to support versions of Minecraft from 1.2.5 to **1.12**, quote from their [site](https://ely.by): "We have developed and will continue to develop patches for all major and popular versions of Minecraft (1.2.5 - 1.12).", which is likely to be incompatible with newer versions of the game and is a miracle it works in any capacity.  
Also, when you are going to get back to the launchers using official auth, I recommend using [PrismLauncher](http://github.com/PrismLauncher/PrismLauncher) as it is the updated and improved verion of MultiMC

**Comment by S0LiD-ST4T3** [comment]
> If you _are_ using ely.by for skins and authentication, they only seem to support versions of Minecraft from 1.2.5 to **1.12**, quote from their [site](https://ely.by): "We have developed and will continue to develop patches for all major and popular versions of Minecraft (1.2.5 - 1.12).", which is likely to be incompatible with newer versions of the game and is a miracle it works in any capacity. Also, when you are going to get back to the launchers using official auth, I recommend using [PrismLauncher](https://github.com/PrismLauncher/PrismLauncher) as it is the updated and improved verion of MultiMC

I do not use the ely.by system in the launcher. i use a "Local Account" (ie, no account) instead, as i substitute the skins system with CPM/MPM and Imgur links usually.

PrismLauncher will be installed, if it supports linux.

**Comment by S0LiD-ST4T3** [comment]
Procuring a surrogate mods folder from another user with a working client, i have encountered a new error.

[crash-2023-01-24_19.12.19-client.txt](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/files/10495284/crash-2023-01-24_19.12.19-client.txt)

rendering screen. yup. 
I switched launchers as well. i trust Prism enough to run on my system.

Maybe it's just my operating system? maybe it's the launcher, i have no idea. but Stock prism in demo mode still crashes.

Hope to scrounge up some money for the game very soon to test further on other launchers.

Perhaps i can find a way to install fabric on ubuntu with the vanilla launcher?

Side note: all other mods on fabric work EXCEPT FOR figura. When figura is removed, the game will start and enter a world normally.

i have no idea why it's doing this... Code audit time?

**Comment by Fnige** [comment]
>  and i'm stuck between bedrock and an equally hard place

What version of bedrock? If its the windows 10 edition, then you should have Java for free iirc

> I have no idea. fabric devs won't help because of.... dumb reasons...

Helping you out in this situation would in fact break discord TOS. Hence why it isnt often you find a discord server that will help you out

---

Can you try installing GLFW 3.3.7 (Given you are on an ubuntu based distro uhhh good luck :+1: (Iirc they have 3.3.6, mightve changed since ~11 days ago)). Once you have installed it, try using that instead

But I can not reproduce this over here too

**Comment by S0LiD-ST4T3** [comment]
Turns out, using cracked minecraft was the issue. That's some fine sabotage, unless it wasn't intentional.
Loading in with an account that actually owns the game, it seems to be stable.

### RESOLVED!!!
...i just needed $30

> What version of bedrock? If its the windows 10 edition, then you should have Java for free iirc

When did this become a bedrock talk? i said that because bedrock is unusually hard, and i wanted to be a little funny. Fuck the bedrock version, i run java edition. I grew up on java, and i will never abandon it.
> Helping you out in this situation would in fact break discord TOS. Hence why it isnt often you find a discord server that will help you out

it won't break TOS anymore. i just bought the game again for the 3rd(?) time...
> Can you try installing GLFW 3.3.7 (Given you are on an ubuntu based distro uhhh good luck +1 (Iirc they have 3.3.6, mightve changed since ~11 days ago)). Once you have installed it, try using that instead

GLFW 3.3.2 is the only available package for ubuntu 20.04, and i don't know how to use cmake, and the root partition is too small for the upgrade to 22.04. neex 6 gigs free to do it.
> But I can not reproduce this over here too

Because you had a legitimate copy. Clearly it seems to work if you run legit MC... I don't know if it's intentional or not, but it crashes on a cracked copy. just makes offline development harder to do.

sorry for causing such trouble...
I have no idea still how to work Github issues, so please close this for me if you're more capable of actually seeing the button for it.

**Comment by applejuiceyy** [comment]
There would be far more issues with the same logs if the mod were set to crash willingly without a verified account
Your launcher is probably modifying your Minecraft installation without consent

**Comment by Fnige** [comment]
> Turns out, using cracked minecraft was the issue. That's some fine sabotage, unless it wasn't intentional.

> I don't know if it's intentional or not, but it crashes on a cracked copy. just makes offline development harder to do.

I mean I'm pretty sure Figura does depend on Microjang's authentication system (Iirc fran uses Reauth in dev environment probably for this reason) so not too surprising. And also what apple said, as cracked launchers very often do that

> When did this become a bedrock talk? i said that because bedrock is unusually hard, and i wanted to be a little funny. Fuck the bedrock version, i run java edition. I grew up on java, and i will never abandon it.

Given from the message, I thought you had Bedrock edition and not Java edition

> GLFW 3.3.2 is the only available package for ubuntu 20.04, and i don't know how to use cmake, and the root partition is too small for the upgrade to 22.04. neex 6 gigs free to do it.

Ah moment. If you ever get some weird error like stack smashing or something else idk (From what we can tell, tends to happen in more content heavy packs). Feel free to scream out, we might be able to find the coremod a friend made for someone elses situation (It just gives minecraft 3.3.8 or 3.3.7 which it would complain about lol)

**Comment by S0LiD-ST4T3** [comment]
I found the "Close Issue" button. Should i close this now?

and i would like that coremod just in case, yes. it'll go in the bucket of contingency plans.

**Comment by Fnige** [comment]
Yeah go for it

And also this is it, make sure that when you install it. Install it as a core mod and not a fabric/forge mod (Who knows if it will work in future versions but hopefully by then LWJGL 3.3.2 is out which contains the wanted GLFW version)
https://cdn.discordapp.com/attachments/1060149593385472030/1062682735287746581/updated-glfw.jar

If you want to try and find a situation where its needed, iirc you can get it to happen by installing AOF5. And trust us, we could not find the mod that caused it (Possibly because no mod caused it)
