### ISSUE TITLE
The "ignoredTexrues" get broken.

### ISSUE THREAD

**Issue by Gakuto1112** [Kingdom-of-The-Moon/FiguraRewriteRewrite#57]
# Description 
The textures which are unused but needed to make avatar can be removed with ``ignoreTextures`` field in ``avatar.json``. However, the textures removed with this way gets broken.

The broken texture appears to show the entire texture every 1 pixel. In other words, a large number of small textures are displayed on the model.

![The broken texture](https://user-images.githubusercontent.com/90630001/215344732-8de8fcac-336f-4ba9-a561-1c30b5015dad.png)

# How to reproduce
1. Make an avatar.
2. Replace a texture using ``models.<path_to_custom_model_part>:setPrimaryTexture()``.
3. Remove the original texture by adding ``ignoredTextures`` filed in ``avatar.json``.
4. You will see the texture broken.

This is an example avatar for reproducing this issue. This avatar make the player into a zombie model. The zombie texture is gotten from the game resource using  ``models.<path_to_custom_model_part>:setPrimaryTexture()``, but the texture is broken.

[Example avatar](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/files/10530417/IgnoreTextureTest.zip)

# Enveronments
- Minecraft 1.19.3
- Fabric loader 0.14.12
- Fabric API 0.72.0+1.19.3
- Figura 0.1.0-rc.13

# Note
I asked the question related from this issue but I could not get any answer, but I suspect that this is a bug.

**Comment by MichiruAvali** [comment]
I have basically the same issue, my avatar has their texture just scattered all over it completely random
