### ISSUE TITLE
Incompatible with Super Secret Revival mod

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Kingdom-of-The-Moon/FiguraRewriteRewrite#61]
https://mclo.gs/IIzCfa3

**Comment by Aces-and-Jacks** [comment]
like when I click the + button

**Comment by lenrik1589** [comment]
I believe this issue has been fixed in the newer version (it appears that you are using latest release, and the issue has been fixed in commits), could you try running [latest build](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/actions/runs/4145872930)?

**Comment by lenrik1589** [comment]
Note, however, that many avatars will not work in this build because of changes introduced in the time since last release.

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/VLWAEbr

used figura-0.1.0-rc.13+1.19.2.jar but issue still occurred

**Comment by Aces-and-Jacks** [comment]
I'll try on a fresh instance. maybe there's a mod conflict

**Comment by Aces-and-Jacks** [comment]
yup. conflict

**Comment by Aces-and-Jacks** [comment]
I'll message when I find it

**Comment by lenrik1589** [comment]
If you know how to do it, could you add JVM flag -Dmixin.debug = true and send output of that? It would show which mod added the mixin that causes the error.

**Comment by Aces-and-Jacks** [comment]
I was just gonna do a binary search. would I put that as an argument?

**Comment by Aces-and-Jacks** [comment]
I've never used java arguments

**Comment by lenrik1589** [comment]
Yes, since you are using Prism Launcher it would just go in instance settings, Java, Java arguments and add `-Dmixin.debug.verbose=true` into it. (oops, just figured out that with just `-Dmixin.debug=true` some mods may cause game to crash)

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/MjhlGju

**Comment by Aces-and-Jacks** [comment]
dang. almost 10k lines of code

**Comment by lenrik1589** [comment]
I am confused, it appears that the function that fails is generated by mixin, but it is not created at runtime?

uhm, is there any mod that would change ui behavior (or more of sounds)?

**Comment by Aces-and-Jacks** [comment]
like a mod that adds sounds?

**Comment by Aces-and-Jacks** [comment]
not any sound mods that I have. I'll just continue with the binary search

**Comment by lenrik1589** [comment]
found the issue

**Comment by Aces-and-Jacks** [comment]
what mod?

**Comment by lenrik1589** [comment]
I don't know what mod is using that information, but pressing any button with an icon instead of text will crash your game because their message is currently being set to `null` instead of `Component.empty()`.

**Comment by Aces-and-Jacks** [comment]
ah...well i'll continue looking then

**Comment by Aces-and-Jacks** [comment]
FINALLY. after a while I found the issue. Super Secret Revival is the mod

**Comment by lenrik1589** [comment]
Huh? Why would something like that mixin into base class? I'll look into  what they are doing, but it *does* seem like not something they should be doing?

**Comment by Aces-and-Jacks** [comment]
And it's the only mod I can't make an issue on either

**Comment by Francy-chan** [comment]
> Huh? Why would something like that mixin into base class? I'll look into what they are doing, but it _does_ seem like not something they should be doing?

this https://git.oat.zone/oat/super-secret-revival/src/branch/1.18/src/main/java/zone/oat/supersecretrevival/mixin/CancelClickSoundMixin.java

**Comment by lenrik1589** [comment]
~~As an alternative, Figrua provides functional of enabling post render effects if you wish to have that~~

**Comment by Aces-and-Jacks** [comment]
I'm guessing it'd be something they need to do on their end so I'll just close this

**Comment by Aces-and-Jacks** [comment]
Unless anyone else knows how to post an issue there

**Comment by lenrik1589** [comment]
working on it

**Comment by Aces-and-Jacks** [comment]
Would sending an email to her GitHub profile be a bad way to do it?

**Comment by lenrik1589** [comment]
The developer of Super Secret Revival has been contacted and confirmed that it'll fix the bug soon ("sometime later today, hopefully")

**Comment by Aces-and-Jacks** [comment]
Got it, thanks. Even though this was an issue I was having and it wasn't from the figura mod, you've been an incredible help

**Comment by oatmealine** [comment]
hi! yes - i'll fix this in the near future, sorry for the troubles!! (i'm hoping filing issues on my git instance will become a lot less difficult once federation rolls around..)

in the future, you could always just ping me on github instead!

**Comment by Aces-and-Jacks** [comment]
> in the future, you could always just ping me on github instead!

I've only done commenting on GitHub repositories...actually I forgot about the @ function. Any future issues I'll do that then

**Comment by oatmealine** [comment]
[1.3](https://modrinth.com/mod/super-secret-revival/version/1.3%2B1.19) shooould fix this unless i've royally messed something up
