### ISSUE TITLE
[Bug?] Skin aren't dispalyed on cracked servers

### ISSUE THREAD

**Issue by enzomtpYT** [Kingdom-of-The-Moon/FiguraRewriteRewrite#62]
Hi ! Im on a heavely modded server wich insn't in offline mode (cracked), and i tried to use figura, it didn't worked !

I think it might be an issue with uuids or something like this !

![image](https://user-images.githubusercontent.com/40535918/219972239-8272bf3c-24ef-42cb-b490-b7f2677318b4.png)

Also in the trust tab figura tells me nobody have the mod (while in fact everyone has it) :

![image](https://user-images.githubusercontent.com/40535918/219972391-613d66e7-233b-4ac2-b145-fc3fb340442a.png)

**Comment by applejuiceyy** [comment]
you need a Minecraft account and an online mode server to be able to use the backend features

**Comment by enzomtpYT** [comment]
There is no way to use it on offline mode server ? (the server also has figura installed)

**Comment by ElectricDaFearox** [comment]
> There is no way to use it on offline mode server ? (the server also has figura installed)

Figura does not work serverside, it is a clientside only mod. And yes there is no way to use it on a Offline Mode server.

**Comment by applejuiceyy** [comment]
no

**Comment by enzomtpYT** [comment]
Ok thanks !
