### ISSUE TITLE
[Bug] unable to chat on certain servers when using with chat patches

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Kingdom-of-The-Moon/FiguraRewriteRewrite#66]
https://mclo.gs/WeEwINF

1.19.2
quilt
Tried to chat on visit.uncensoredlibrary.com server. Crashed

**Comment by lenrik1589** [comment]
I do not see neither viaversion nor multiconnect (it is disabled) on in that log, making me doubt that that is the correct log as `visit.uncensoredlibrary.com` reports to be 1.16.5 server, as well as it has no "crash" header and process exit code is 0, indicating normal exit. Please check if you uploaded the correct log file

**Comment by Aces-and-Jacks** [comment]
Sorry I copied from another issue from a different mod that I discovered a problem with on that server and altered it. And that server says it's 1.16.5 but it works on 1.19.2.

It doesn't make me crash but it makes me unable to chat on that server and others like it. If you look at line 4138 to 4307 that error shows whenever I type in chat

**Comment by Aces-and-Jacks** [comment]
Probably needed but https://mclo.gs/rKoMZrJ is without figure added and chat works normally

**Comment by Aces-and-Jacks** [comment]
It's probably a server plugin that affects it, so I'm not really sure if it's something fixable on the mods end

**Comment by lenrik1589** [comment]
Could you please try with figura but without chat patches?

**Comment by lenrik1589** [comment]
> Sorry I copied from another issue from a different mod that I discovered a problem with on that server and altered it. And that server says it's 1.16.5 but it works on 1.19.2.

Also, I was unable to access the server from 1.19.3 and *in my experience* when a server is using a packet translator it will show the highest allowed version instead of original version

**Comment by Aces-and-Jacks** [comment]
1.19.3 doesn't work 1.19.2 does. At least from when I remember going on. I'll try without chat patches

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/NiP7jup

Well...I guess it has something to do with chat patches and figura. However they usually work fine together. I'll make an issue on chat patches then

**Comment by lenrik1589** [comment]
So it is at least three way incompatibility with something else, *how fun*…

**Comment by Aces-and-Jacks** [comment]
Like a server plugin?

**Comment by Aces-and-Jacks** [comment]
2 mods and a plugin

**Comment by lenrik1589** [comment]
It may be a mod providing extra functionality for some server mod/plugin, so yes

**Comment by mrbuilder1961** [comment]
hi, i'm the owner of Chat Patches, and i think what's happening is the `addMessage` ModifyVariable injector in `ChatComponentMixin` is loaded ***after*** CP's equivalent `modifyMessage` injector. my mod restructures messages into an empty text with an appended timestamp, message, and duplicate counter as children in that order. what's probably happening is this mod modifies the message *after* mine, which effectively removes the ordering and ends up throwing an error when the duplicate counter check runs. 

i can try finding a way to load the mixin after this, but i'll have to do some digging.

i'll go put a temporary fix on my issue.

**Comment by lenrik1589** [comment]
> i can try finding a way to load the mixin after this, but i'll have to do some digging.

The only way i know of how to do this is to have higher priority on the `@Mixin`, the default is 1000 and i see that your mixin is explicitly made to load earlier with priority 400

**Comment by mrbuilder1961** [comment]
okay i'll increase the default prio for all mixins to 2000 just in case

**Comment by Aces-and-Jacks** [comment]
Issue fixed I think with chat patches new fix so I'll close
