### ISSUE TITLE
GUI completely decimated

### ISSUE THREAD

**Issue by mageowl** [Kingdom-of-The-Moon/FiguraRewriteRewrite#7]
<img width="1086" alt="Screen Shot 2022-07-24 at 6 53 43 AM" src="https://user-images.githubusercontent.com/32573897/180650335-407ee097-6f27-4e25-922c-45f436f4fd81.png">
<img width=
<img width="1019" alt="Screen Shot 2022-07-24 at 6 40 18 AM" src="https://user-images.githubusercontent.com/32573897/180650340-f2874d03-e1f3-4671-af04-267f69a60e67.png">
<img width="926" alt="Screen Shot 2022-07-24 at 6 40 28 AM" src="https://user-images.githubusercontent.com/32573897/180650338-07b08d14-1628-45f8-bb44-2ed6b6a17f71.png">
<img width="1321" alt="Screen Shot 2022-07-24 at 6 40 24 AM" src="https://user-images.githubusercontent.com/32573897/180650339-a8def702-0b8d-4254-9171-9af7659416a1.png">

Both Mod Menu and the in-game panel are not working. Avatars rendering fine. Possibly not working b/c it was on a bigger screen before? (i use a monitor sometimes, and it was working then.) MacOS and Figura both on latest version.

**Comment by mageowl** [comment]
**Not a mod conflict.**

**Comment by mageowl** [comment]
## Workaround:
Use [sodium extra](https://www.curseforge.com/minecraft/mc-mods/sodium-extra)

Thanks @Francy-chan.

**Comment by Francy-chan** [comment]
fixed with e920b43d8c6ff1ec5a12eeb1e3c5f5f37dac8d66
