### ISSUE TITLE
"Skull" parent type is not hidden even when its parent part is hidden

### ISSUE THREAD

**Issue by Gakuto1112** [Kingdom-of-The-Moon/FiguraRewriteRewrite#70]
# Description
"Skull" parent type is not hidden even when its parent part is hidden. For example, assume that there is a model with following structure.

```
model.bbmodel
└ Skull
  └ Head
```

After running `models.model:setVisible(false)`, `models.model` will be hidden and `models.model.Skull` also should be hidden because `models.model.Skull`'s visibility is not specified, so just follow parent's visilility. However, `models.model.Skull` is not hidden even in this situation.

# How to reproduce
1. Create a model with a structure like above.
2. Apply this avatar as your Figura avatar.
3. Get your player head by running `/give @p minecraft:player_head{SkullOwner:"<your_player_name>"}`.
4. Put your head.
5. Hide head's parent by running `/figura run models.model:setVisible(false)`.
6. You will see your head model even it is hidden.

An example avatar for reproduction is attached this issue. This avatar turns host player head into zombie's one, and has action wheel to show/hide skull model and show skull visibility.

![The screenshot which shows this issue](https://user-images.githubusercontent.com/90630001/225801505-74fad976-434d-4c98-9781-8f24f04ae649.png)

# Enveronments
- MacOS Ventura 13.2.1
- Minecraft 1.19.4
- Fabric Loader 0.14.17-1.19.4
- Fabric API 0.75.3+1.19.4
- Figura 0.1.0-rc.14

# Notes
- [An example avatar](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/files/10997449/SkullVisibleTest.zip)
- I confirm this issue with "Skull" parent type but there may be more than this.

**Comment by Francy-chan** [comment]
based on 77b459f, that work as inteded
