### ISSUE TITLE
[Issue] Invalid discord link

### ISSUE THREAD

**Issue by LDev-IX** [Kingdom-of-The-Moon/FiguraRewriteRewrite#71]
Please update the discord link on those pages:
- [Modrinth](https://modrinth.com/mod/figura)
- [Github Repo](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite)

**Comment by skyrina** [comment]
the discord links are correct.

**Comment by lenrik1589** [comment]
> Please update the Discord link  

Could you enlighten us as to what would be an up-to-date link is?
