### ISSUE TITLE
Apply a dedicated model created on the server

### ISSUE THREAD

**Issue by nea-c** [Kingdom-of-The-Moon/FiguraRewriteRewrite#77]
A server-side mod that allows you to adapt the avatar created in the server folder by command

**Comment by lenrik1589** [comment]
`closed`

**Comment by ElectricDaFearox** [comment]
To give an honest answer, while the concept is pretty nice. I don’t want to give servers any power over Figura. It ruins the goal of Figura in my honest opinion.
