### ISSUE TITLE
Avatar arms see through

### ISSUE THREAD

**Issue by joeyak** [Kingdom-of-The-Moon/FiguraRewriteRewrite#81]
When rendering my avatar, you can see through the hands.
![image](https://user-images.githubusercontent.com/27922090/234998952-11da44d4-efaf-4c65-8371-1b8ca2951f13.png)

It also shows up in block bench...so I'm not sure if it's a bug in the model or what...
![image](https://user-images.githubusercontent.com/27922090/234999044-0553a0f2-dc33-43a7-83e7-7f11a5e837f4.png)

Here's my avatar folder
[avatar.zip](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/files/11348235/avatar.zip)

**Comment by skyrina** [comment]
Dear @joeyak,

I hope this message finds you well. I noticed that you have asked a question in our GitHub issues section, and while we appreciate your engagement and curiosity, we kindly ask that you refrain from doing so in the future. 

Our GitHub issues section is reserved for reporting bugs and suggesting feature enhancements. We encourage all users to instead ask questions and engage with our community on our [Discord server](https://discord.gg/moonlight-mc), where you can find a more suitable platform for such discussions. Our team and other members of the community will be more than happy to assist you and provide answers to any questions you may have.

Thank you for your understanding and cooperation in this matter.

Best regards,
@skyrina

**Comment by joeyak** [comment]
Thank you for your timely response, however, this actually is a bug. Here you can see that the model is rendering incorrectly.
![image](https://user-images.githubusercontent.com/27922090/235105771-55614b95-ec64-48cb-bc4a-8c9a9625c6fd.png)

Here is another view with the same issue.
![image](https://user-images.githubusercontent.com/27922090/235108130-9e740d63-c232-4f0f-8769-f9ceb7b6e4f7.png)

What I did was create a minecraft skin in blockbench, use my normal mc's skin texture, and then convert it to a generic model, and save it to the `.minecraft\figura\avatars\Void` folder with a `script.lua` containing `vanilla_model.PLAYER:setVisible(false)` and an `avatar.json` containing `{}`. I redid the steps into `.minecraft\figura\avatars\Void2` and found the same issue.

**Comment by skyrina** [comment]
ah, i didn't see that.
this is a minecraft bug related to transparent textures.
i do not believe there is a way to fix this without modifying the minecraft renderer itself, which could break compatibility with other mods.

**Comment by joeyak** [comment]
Ah I see. I was wondering if it was because the transparent layer. That makes sense... I think it's unintended functionality in minecraft. Thank you!

**Comment by joeyak** [comment]
I just wanted to follow up because I found the issue... I had the Steve model but it was an Alex skin....
