### ISSUE TITLE
When you start the world, the game closes

### ISSUE THREAD

**Issue by QueenUlyana** [Kingdom-of-The-Moon/FiguraRewriteRewrite#87]
When you start the world, the game closes
figura-0.1.0-rc.14+1.19.4.jar
[5467.txt](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/files/11584566/5467.txt)

**Comment by lenrik1589** [comment]
Can you check if the same happens on the latest build (in the Actions)?

**Comment by skyrina** [comment]
we don't support cracked launchers. buy the game.

**Comment by QueenUlyana** [comment]
> Can you check if the same happens on the latest build (in the Actions)?

What is the "Actions" build? I don't know

**Comment by lenrik1589** [comment]
Also, is your account pirated or something? I don't think "`<КЛЮЧ ДОСТУПА>`" is a valid username (oh cool, sky closed it :>)
