### ISSUE TITLE
[Bug] Emissive textures do not seem to respect ModelPart:setVisibility

### ISSUE THREAD

**Issue by Ulhar** [Kingdom-of-The-Moon/FiguraRewriteRewrite#90]
~~If a part is marked as visible within Blockbench, and it has emissive textures on it, then those emissive textures will always be visible on the model, even if the part in question is marked invisible by the script (although setting the part's secondary render type to NONE might relieve this); likewise, if a part is marked invisible, then emissive textures will not render on it even if scripts make it visible (and changing secondary render type won't help)~~ (edit: there was no bug, I just made a rather silly error)

- Minecraft version: 1.19.4
- Figura version: 0.1.0 rc14
- Modloader: Quilt 0.18.10

**Comment by KitCat962** [comment]
Do you have any other mods installed? Or is the only difference from normal install the Quilt loader?

**Comment by KitCat962** [comment]
I cannot replicate this behavior with the setup you provided. Its probably a mod incompatibility
```lua
vanilla_model.ALL:setVisible(false)
models.model.root.Head:setVisible(false)
```
![image](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/assets/94943674/d72ba0a4-a66f-4cac-963f-dc60471c72a5)
![image](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/assets/94943674/fd919bf9-7d70-43e7-9c23-73682cd678e4)

**Comment by Ulhar** [comment]
Perhaps it may have some effect that I was toggling not the Head group, but individual items within that group? (i.e. specific cubes, with a setup like shown below, where each cube has a different facial expression)
![image](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/assets/37605131/98e4d2d4-ca93-4df1-a8e3-d74008916dfb)

Testing on my own, it does seem at least to respect visibility rules when a parent group is hidden (i.e. `models:setVisible(false)` to hide all custom models)

As for mods, I have these installed: `Continuity, Enhanced Attack Indicator, Figura, Indium, Inspecio, Krypton, LambdaBetterGrass, Language Reloade, LazyDFU, Lithium, Mod Menu, Phosphor, Presence Footsteps, Screenshot to Clipboard, Sodium` (all on latest version on Modrinth)

**Comment by KitCat962** [comment]
I've tested on cubes, but I did not get any other outcome. I'm pretty sure `models` has some unique code with it that blocks all rendering for performance reasons. Can you try with the Head group? Also, can you show how you are doing emissives?

I'll test with the other mods shortly

**Comment by KitCat962** [comment]
Even with your modlist I have yet to have the bug occur. Can you provide screenshots depicting the bug? Also, I *really* want to see how you are doing emissives.

**Comment by Ulhar** [comment]
...I just realized I renamed my model file, but kept saving to the old one, so I was referring to the new name in code (which hadn't gotten emissives attached yet) but only the old one had emissives, so this is completely a mixup on my part 😅 Once I fixed the naming error though, everything worked out as it should have, so there isn't actually a bug here 👍
