### ISSUE TITLE
3 Pixel Arm "Alex Skins" Not Rendering Properly

### ISSUE THREAD

**Issue by Bizzlechap** [Kingdom-of-The-Moon/FiguraRewriteRewrite#91]
When I port my model from Blockbench to the Figura folder, the skin is turned into a 4 pixel arm skin.
Here is the model in BB:
![image](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/assets/74218470/1a14e482-6fb6-4cc9-ad37-d68c05fb32e6)
Here is the model in MC:
![image](https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/assets/74218470/b48714d5-92c4-457a-b97c-afd58784085f)

The only thing that I could think of is somehow when porting the "skin model" to "generic model" in BB affects the model when ported to MC.

**Comment by KitCat962** [comment]
Have you hidden the vanilla model via script? It looks like there is z fighting. 

Also, what you see in blockbench is what you get in figura. If as a generic model the model is 3 pixels wide, then it will be 3 pixels wide in-game.

**Comment by Bizzlechap** [comment]
Ah. I see what I did. For some reason, a while back while uploading my skin, I selected the "classic model." Nothing to do with the mod, which is good. Sorry for the inconvenience.
