### ISSUE TITLE
Skill issue when creating custom server avatar

### ISSUE THREAD

**Issue by Temm4ancki** [Kingdom-of-The-Moon/FiguraRewriteRewrite#98]
I don't understand how to force the figure to connect to my avatars server. 
I use the server from this [github](https://github.com/Moonlight-MC/FiguraServer), but minecraft just doesn't see this server. If you access it from a browser, then there is at least some answer. 

Am I an idiot who doesn't understand something or is it just not provided?

**Comment by Slymeball** [comment]
Th... That's the prewrite's backend...

FOR CONTEXT: Prewrite is versions 0.0.8 and below. The backend used in those versions are completely incompatible with 0.1.0 versions.

**Comment by Temm4ancki** [comment]
Can I make my own server for the current version that will work on the server with the online mod turned off? Or at least some way to make the mod work on the server with the online mod turned off

We just have the majority on the server with bought minecraft, but there are a couple of people with cracked minecraft. I wanted at least the mod to work for the person with the purchased minecraft

**Comment by Temm4ancki** [comment]
Can I make my own server for the current version that will work on the server with the online mod turned off? Or at least some way to make the mod work on the server with the online mod turned off

We just have the majority on the server with bought minecraft, but there are a couple of people with cracked minecraft. I wanted at least the mod to work for the person with the purchased minecraft

**Comment by Francy-chan** [comment]
as long you provide the users in your server with their actual uuid, instead of the name-based uuid from offline servers, figura will work perfectly for them

**Comment by kcin2001** [comment]
> Can I make my own server for the current version that will work on the server with the online mod turned off? Or at least some way to make the mod work on the server with the online mod turned off
> 
> We just have the majority on the server with bought minecraft, but there are a couple of people with cracked minecraft. I wanted at least the mod to work for the person with the purchased minecraft

This is exactly the reason the current one wenr closed source

**Comment by Temm4ancki** [comment]
Okay. Thanks guys
